### ISSUE TITLE
Call Me Maybe - Unable to verify solution

### ISSUE THREAD

**Issue by snowinferno** [workshopper/goingnative#64]
I've added the appropriate code to my module, it compiles fine with node-gyp rebuild and runs exactly as expected when I run it with `node . <time in ms>` however when time I try to verify I get the following message.

I'm running this using nvm installed node v0.10.40, npm 2.14.2, and node-gyp v3.0.3

message:
```
$goingnative verify myaddon
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
  CXX(target) Release/obj.target/myaddon/myaddon.o
  SOLINK_MODULE(target) Release/myaddon.node
  SOLINK_MODULE(target) Release/myaddon.node: Finished
  CXX(target) Release/obj.target/myaddon/myaddon.o
../myaddon.cc:10:45: error: no matching function for call to 'To'
  Nan::MaybeLocal<Function> maybeCallback = Nan::To<Function>(info[1]);
                                            ^~~~~~~~~~~~~~~~~
../node_modules/nan/nan_converters.h:53:38: note: candidate template ignored: substitution failure [with T = v8::Function]: implicit instantiation of undefined template
      'Nan::imp::ToFactory<v8::Function>'
typename imp::ToFactory<T>::return_t To(v8::Local<v8::Value> val) {
~~~~~~~~                             ^
1 error generated.
make: *** [Release/obj.target/myaddon/myaddon.o] Error 1
✗ Compile mock C++ to test JavaScript: node-gyp build: `make` failed with exit code: 2

# FAIL

Your solution to CALL ME MAYBE didn't pass. Try again!
```

myaddon.cc:
```
#include <nan.h>

#ifndef _WIN32
#include <unistd.h>
#endif

using namespace v8;

NAN_METHOD(Delay) {
	using Nan::To;
	using Nan::MaybeLocal;
	Nan::HandleScope scope;
	MaybeLocal<Number> maybeNum = To<Number>(info[0]);
	if (maybeNum.IsEmpty() == false) {
		int64_t sleep_time = maybeNum.ToLocalChecked()->IntegerValue();
		#ifdef _WIN32
		Sleep(sleep_time);
		#else
		usleep(sleep_time * 1000);
		#endif
		Local<Function> callback = info[1].As<Function>();
		Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callback, 0, NULL);
	}
}

NAN_MODULE_INIT(Init) {
  Nan::Set(target, Nan::New("delay").ToLocalChecked(),
	  Nan::GetFunction(Nan::New<FunctionTemplate>(Delay)).ToLocalChecked());
}

NODE_MODULE(myaddon, Init)
```

**Comment by kkoopa** [comment]
Hmm... I don't see anything like `Nan::MaybeLocal<Function> maybeCallback = Nan::To<Function>(info[1]);` on line 10. However, there is no `To<Function>`, as you can't convert something to a `Function`. It is however possible to do `As<Function>()` or `Function::Cast`.

Also, you don't need an explicit scope in a v8-exposed method, there is already one provided from the transition from JavaScript to C++.

**Comment by snowinferno** [comment]
The error seems to indicate that the error is in the mock, I think it might be referring to this but am not sure what the fix should be: https://github.com/workshopper/goingnative/blob/master/exercises/call_me_maybe/faux/myaddon.cc#L10

I presume your note about an explicit scope is referring to my line 12: `Nan::HandleScope scope;`. The previous exercise "It's a two-way street" indicated that the scope should be there unless my understanding of the note on scopes the exercise provides is flawed. If it is automatic, that makes life easier and I'll happily chug along without including the scope in the NAN_METHOD declaration.

```
...
Next we need to tackle the tricky concept of V8 scopes.

C++ doesn't have automatic garbage collection, but JavaScript does. V8 tries to bridge the gap by providing an environment in C++ where your objects interact directly with the garbage collector, even if they are created in C++.

It's not a fully automatic process unfortunately. To replicate the concept of function scoping of variables, V8 introduces a HandleScope. When you declare a HandleScope at the top of a C++ function, all V8 objects created within that function will be attached to that scope in the same way that a function in JavaScript will capture new variables declared within it.

To declare one of these scopes in your code, use Nan::HandleScope scope; call at the top of your function. When your function ends, the scope can then pass on the objects to the garbage collector if they have not been passed outside of the scope.
...
```

**Comment by kkoopa** [comment]
Ah, I see. The fix would be to first check `info[1]->IsFunction()`, throw on `false`, and do `info[1].As<Function>()` if `true`.

That documentation is slightly wrong / outdated. It's missing this part https://github.com/nodejs/nan/blob/master/doc/scopes.md#api_nan_handle_scope

> Note that an implicit HandleScope is created for you on JavaScript-accessible methods so you do not need to insert one yourself.
> Example:
```c++
// new object is created, it needs a new scope:
void Pointless() {
  Nan::HandleScope scope;
  v8::Local<v8::Object> obj = Nan::New<v8::Object>();
}

// JavaScript-accessible method already has a HandleScope
NAN_METHOD(Pointless2) {
  v8::Local<v8::Object> obj = Nan::New<v8::Object>();
}
```

**Comment by snowinferno** [comment]
I made the suggested change to the faux/myaddon.cc in my installed modules directory but I'm getting a different error that doesn't make sense to me but it seems to be pointing at my js code.

To all appearances, the verification for this exercise is broken, at least on OSX Yosemite.

```
goingnative verify myaddon
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
  CXX(target) Release/obj.target/myaddon/myaddon.o
  SOLINK_MODULE(target) Release/myaddon.node
  SOLINK_MODULE(target) Release/myaddon.node: Finished
  CXX(target) Release/obj.target/myaddon/myaddon.o
  SOLINK_MODULE(target) Release/myaddon.node
  SOLINK_MODULE(target) Release/myaddon.node: Finished

/Users/snowinferno/learning/~test-addon-faux.5646/index.js:8
addon.delay(arg, function() {
      ^
TypeError: Object #<Object> has no method 'delay'
    at Object.<anonymous> (/Users/snowinferno/learning/~test-addon-faux.5646/index.js:8:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
Could not verify: Command failed:
/Users/snowinferno/learning/~test-addon-faux.5646/index.js:8
addon.delay(arg, function() {
      ^
TypeError: Object #<Object> has no method 'delay'
    at Object.<anonymous> (/Users/snowinferno/learning/~test-addon-faux.5646/index.js:8:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by kkoopa** [comment]
That error makes little sense as well.
A method named 'delay' is clearly exported here https://github.com/workshopper/goingnative/blob/master/exercises/call_me_maybe/faux/myaddon.cc#L37-L38 as well as in the code you originally posted.
The addon also seems to be loaded by require, since this line passes: https://github.com/workshopper/goingnative/blob/master/exercises/call_me_maybe/faux/index.js#L1

**Comment by julianduque** [comment]
Landed in `2.0.4` thanks!

**Comment by iamstolis** [comment]
It is nice that the mock files are fixed but it would be great to apply similar changes also to exercise solutions as they have the same problem.

**Comment by snowinferno** [comment]
@iamstolis Excellent point, I can't believe I overlooked that. I'll get that updated and and send another PR.
