### ISSUE TITLE
Call Me Maybe - having multiple issues

### ISSUE THREAD

**Issue by kgraves** [workshopper/goingnative#69]
First, I just want to say that I'm liking this package, so thanks for this! :beer:
However I'm having the following issues with this challenge:
- The instructions say:

  > Use the `handle->IntegerValue()` method, which returns a `int64_t` type value.

  However when you complete the challenge, the official solution doesn't use this function. This confused me a little bit. This confusion led me to the next issue.
- The official solution doesn't compile for me. I copied the official solution file into `myaddon/` directory and tried running `$ node-gyp rebuild` within the `myaddon/` directory. I get the following errors:

  ```bash
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.0
gyp info using node@5.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kg/Documents/gits/goingnative-lessons/myaddon/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kg/.node-gyp/5.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/kg/.node-gyp/5.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/kg/Documents/gits/goingnative-lessons/myaddon',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp make: Entering directory '/home/kg/Documents/gits/goingnative-lessons/myaddon/build'
info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/myaddon/myaddon.o
../myaddon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Delay(Nan::NAN_METHOD_ARGS_TYPE)’:
../myaddon.cc:10:70: error: no matching function for call to ‘To(v8::Local<v8::Value>)’
   Nan::MaybeLocal<Function> maybeCallback = Nan::To<Function>(info[1]);
                                                                      ^
In file included from ../node_modules/nan/nan.h:199:0,
                 from ../myaddon.cc:1:
../node_modules/nan/nan_converters.h:53:38: note: candidate: template<class T> typename Nan::imp::ToFactory<T>::return_t Nan::To(v8::Local<v8::Value>)
 typename imp::ToFactory<T>::return_t To(v8::Local<v8::Value> val) {
                                      ^
../node_modules/nan/nan_converters.h:53:38: note:   template argument deduction/substitution failed:
../node_modules/nan/nan_converters.h: In substitution of ‘template<class T> typename Nan::imp::ToFactory<T>::return_t Nan::To(v8::Local<v8::Value>) [with T = v8::Function]’:
../myaddon.cc:10:70:   required from here
../node_modules/nan/nan_converters.h:53:38: error: invalid use of incomplete type ‘struct Nan::imp::ToFactory<v8::Function>’
../node_modules/nan/nan_converters.h:18:29: note: declaration of ‘struct Nan::imp::ToFactory<v8::Function>’
 template<typename T> struct ToFactory;
                             ^
myaddon.target.mk:90: recipe for target 'Release/obj.target/myaddon/myaddon.o' failed
make: *** [Release/obj.target/myaddon/myaddon.o] Error 1
make: Leaving directory '/home/kg/Documents/gits/goingnative-lessons/myaddon/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-19-generic
gyp ERR! command "/home/kg/.nvm/versions/node/v5.0.0/bin/node" "/home/kg/.nvm/versions/node/v5.0.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/kg/Documents/gits/goingnative-lessons/myaddon
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok 
$
  ```
  Here's the output when I run `goingnative verify myaddon/` with the official solution in place:
  ```bash
$ goingnative verify myaddon 
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
make: Entering directory '/home/kg/Documents/gits/goingnative-lessons/~test-addon.9565/build'
  CXX(target) Release/obj.target/myaddon/myaddon.o
../myaddon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Delay(Nan::NAN_METHOD_ARGS_TYPE)’:
../myaddon.cc:10:70: error: no matching function for call to ‘To(v8::Local<v8::Value>)’
   Nan::MaybeLocal<Function> maybeCallback = Nan::To<Function>(info[1]);
                                                                      ^
In file included from ../node_modules/nan/nan.h:199:0,
                 from ../myaddon.cc:1:
../node_modules/nan/nan_converters.h:53:38: note: candidate: template<class T> typename Nan::imp::ToFactory<T>::return_t Nan::To(v8::Local<v8::Value>)
 typename imp::ToFactory<T>::return_t To(v8::Local<v8::Value> val) {
                                      ^
../node_modules/nan/nan_converters.h:53:38: note:   template argument deduction/substitution failed:
../node_modules/nan/nan_converters.h: In substitution of ‘template<class T> typename Nan::imp::ToFactory<T>::return_t Nan::To(v8::Local<v8::Value>) [with T = v8::Function]’:
../myaddon.cc:10:70:   required from here
../node_modules/nan/nan_converters.h:53:38: error: invalid use of incomplete type ‘struct Nan::imp::ToFactory<v8::Function>’
../node_modules/nan/nan_converters.h:18:29: note: declaration of ‘struct Nan::imp::ToFactory<v8::Function>’
 template<typename T> struct ToFactory;
                             ^
myaddon.target.mk:90: recipe for target 'Release/obj.target/myaddon/myaddon.o' failed
make: *** [Release/obj.target/myaddon/myaddon.o] Error 1
make: Leaving directory '/home/kg/Documents/gits/goingnative-lessons/~test-addon.9565/build'
✗ node-gyp build: `make` failed with exit code: 2

# FAIL

Your solution to CALL ME MAYBE didn't pass. Try again!
  ```

**Comment by kgraves** [comment]
I just completed the last challenge, 'Offloading The Work', and had the same issue where I was able to complete the challenge, but the official solution doesn't build for the same reasons as above.

**Comment by mpmckenna8** [comment]
Getting the same errors with the official solution on OS X.

**Comment by rvagg** [comment]
solutions should be updated to work with the latest NAN now and _should_ compile and work fine..

the `IntegerValue()` thing is a remnant of an old API that hasn't been changed, the `FromJust()` thing now is required but the docs haven't been updated. I'd welcome a pull request to fix this as I don't have time just now to deal with it.

**Comment by rvagg** [comment]
OK, it bugged me enough that I fixed the doc. Should be all good to go now, thanks for reporting.
