### ISSUE TITLE
Global installation error 

### ISSUE THREAD

**Issue by programerr01** [workshopper/goingnative#94]
when installed globally by command `sudo npm install goingnative -g`
**It gives error**
```
node postinstall.js

internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/goingnative/exercises/am_i_ready/problem.md'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at /usr/local/lib/node_modules/goingnative/postinstall.js:17:6
    at /usr/local/lib/node_modules/goingnative/node_modules/getos/index.js:100:16
    at /usr/local/lib/node_modules/goingnative/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/goingnative/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/goingnative/node_modules/async/lib/async.js:209:22)
    at /usr/local/lib/node_modules/goingnative/node_modules/getos/index.js:80:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/goingnative/exercises/am_i_ready/problem.md'

```

**Comment by kid-icarus** [comment]
@programerr01 There should be no need to use `sudo` in order to install a global module, and that is causing the permission error you see.

Can you uninstall the module, and try reinstalling again, this time without using sudo?

**Comment by essn** [comment]
@programerr01 @kid-icarus I had this issue and it was resolved by omitting `sudo`.
